# Generated by Django 2.2.2 on 2024-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasto_core_clean_arch', '0003_auto_20241018_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
